spring:
  data:
    mongodb:
      uri: "mongodb://mongo:27017"
      database: accountsDb
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  port: 8082

customers:
  service:
    url: lb://customers-msvc

transactions:
  service:
    url: lb://transactions-msvc
logging:
  level:
    root: INFO
    app: DEBUG
    mongo: WARN
  file:
    name: logs/accounts-msvc.log

# Eureka config
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}