spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: customers
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
