spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: customersDb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  port: 8080
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    root: INFO
    app: DEBUG
    mongo: WARN
  file:
    name: logs/customers-msvc.log

accounts:
  service:
    url: lb://accounts-msvc

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}