spring:
  data:
    mongodb:
      uri: "mongodb://mongo:27017"
      database: customersDb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  port: 8080
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    root: INFO
    app: DEBUG
    mongo: WARN
  file:
    name: logs/customers-msvc.log

accounts:
  service:
    url: http://accounts-msvc:8082
