spring:
  data:
    mongodb:
      uri: "mongodb://mongo:27017"
      database: transactionsDb
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  port: 8081

logging:
  level:
    root: INFO
    app: DEBUG
    mongo: WARN
  file:
    name: logs/transactions-msvc.log

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}